# Generated by Django 3.1.5 on 2021-06-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_making', '0002_note_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='id',
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
